apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: tallerproteccion
  name: tallerproteccion
  namespace: tallerdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tallerproteccion
  template:
    metadata:
      labels:
        app: tallerproteccion
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: saludos-proteccion
        ports:
        - containerPort: 80